# Generated by Django 4.1.1 on 2022-10-11 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classActivities', '0004_alter_activity_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grade',
            new_name='ActivityExercise',
        ),
    ]
